name: Deploy portfolio

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install
        working-directory: ./
        run: npm install

      - name: Build
        working-directory: ./
        run: npm run build && cp ./dist/portfolio/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: ./dist/portfolio
